apiVersion: v1
kind: Secret
metadata:
  namespace: ecommerce
  name: external-hosts
type: Opaque
stringData:
  KAFKA_BOOTSTRAP_ADDRESS: 	b-1.ecommerce.n4kxwy.c1.kafka.us-west-2.amazonaws.com:9092,b-2.ecommerce.n4kxwy.c1.kafka.us-west-2.amazonaws.com:9092,b-3.ecommerce.n4kxwy.c1.kafka.us-west-2.amazonaws.com:9092
  LOGISTICS_POSTGRES_HOST: jdbc:postgresql://logistics.cfgoegmtheai.us-west-2.rds.amazonaws.com:5432/postgres
  ORDER_PROCESSOR_POSTGRES_HOST: jdbc:postgresql://orderprocessor.cfgoegmtheai.us-west-2.rds.amazonaws.com:5432/postgres
  ORDER_RECEIVER_POSTGRES_HOST: jdbc:postgresql://orderreceiver.cfgoegmtheai.us-west-2.rds.amazonaws.com:5432/postgres
  PAYMENTS_POSTGRES_HOST: jdbc:postgresql://payments.cfgoegmtheai.us-west-2.rds.amazonaws.com:5432/postgres
  PRODUCT_VIEWER_POSTGRES_HOST: jdbc:postgresql://productviewer.cfgoegmtheai.us-west-2.rds.amazonaws.com:5432/postgres
  STOCK_POSTGRES_HOST: jdbc:postgresql://stock.cfgoegmtheai.us-west-2.rds.amazonaws.com:5432/postgres