apiVersion: v1
kind: Service
metadata:
  namespace: ecommerce
  name: order-receiver
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: order-receiver
---
apiVersion: v1
kind: Service
metadata:
  namespace: ecommerce
  name: logistics
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: logistics
---
apiVersion: v1
kind: Service
metadata:
  namespace: ecommerce
  name: order-processor
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: order-processor
---
apiVersion: v1
kind: Service
metadata:
  namespace: ecommerce
  name: payments
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: payments
---
apiVersion: v1
kind: Service
metadata:
  namespace: ecommerce
  name: productviewer
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: productviewer
---
apiVersion: v1
kind: Service
metadata:
  namespace: ecommerce
  name: stock
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: stock