apiVersion: v1
kind: Secret
metadata:
  namespace: ecommerce
  name: external-hosts
type: Opaque
stringData:
  KAFKA_BOOTSTRAP_ADDRESS: 	xxx
  LOGISTICS_POSTGRES_HOST: jdbc:postgresql://xxx:5432/postgres